### ISSUE TITLE
demo_done, skeleton, kazoocon demos not working

### ISSUE THREAD

**Issue by powerpbx** [2600hz/monster-ui#58]
I have tried all the demos listed above on master branch according to documentation.  None of them will load.  They were named/re-named properly and added to database as app `demo` according to documentation.  Tried manual and automatic methods.  I enabled debugging but the errors are very general.

I was able to rename working apps to `demo` and have them load to confirm my install procedure is correct.

**Comment by JRMaitre** [comment]
Sorry about that, in the process of fixing them with our new way of loading things. Will update in the next day or so :)

**Comment by JRMaitre** [comment]
Hey,

I updated the demos on master with https://github.com/2600hz/monster-ui/commit/4faa8126bd81594d25b0d50029fd2ab1731dc808

Let me know if you still run into any issues.

Thanks for the feedback :)

**Comment by powerpbx** [comment]
Thank you.  Skeleton and demo_done both working now.
